fixtures:
  forge_modules:
    augeasproviders_core: 'hercules-team/augeasproviders_core'
    augeasproviders_shellvar: 'hercules-team/augeasproviders_shellvar'
    stdlib: 'puppetlabs/stdlib'
  symlinks:
    openldap: "#{source_dir}"
