---
.travis.yml:
  extras:
    - rvm: 2.0.0
      env: BEAKER_set="debian-7-x86_64-openstack"
      bundler_args:
      script: "'[ -z \"${OS_AUTH_URL}\" -o -z \"${OS_USERNAME}\" -o -z \"${OS_PASSWORD}\" -o -z \"${OS_TENANT_NAME}\" ] || bundle exec rspec spec/acceptance'"
  forge_password: "ZjmgM4a2tcCE4dtccVSmYZAcuCaXdZNsZxVzRiDg7URBYyALMNgCV6XaiS/DTHX4jCuiyw/89Vywyf+uDjrj1552D+lF3cuQMXziwJhXp9v0jJRT9kpq8CFnq4iC/qwqLj54QIhIFoVgtiY9k+2MWRoMuGveLnAmg9K6wSNvLS4="
  globals:
    - secure: Pzb35J5xuR39hogwvj88nPW1Oo6g/HRZB0SaP6xCIyvhn4xWzVmOExSLH/6IjgmUtMvVpKh+oRACGrIPg2UT2RietMM/XwXzkYjOf7S2RdFBs5T7BMINp1U2yNDHRZ2xAi+8ujxstzm06qJN+3FuiRA9/YqDWnT1Prtfc+09zXM=
    - secure: Uw8xh8bRviyqzdvHjXxhnW2nirxOQ0dRq+/xPmv/buZmnt07ndPn3eGSID2ZtMvkVLlVvu0ADJ0BszveBMYMBy8tgXHTzi4pOb3axVfvDZhT8Jr4SG7C1Izx4OoAj0UqNHckqt5cgIwNw/j35nEP4jqjzE6BEs5KLzwbuxTeslg=
    - secure: YdiihoHec5Un40eZlffJRhFvUHWIBav3dWu1iR+/J1HQ3+dTDd9N04iMEHGvyoz74Wyeq1noxrHxuAMSUdDTfdda0lEuXJI6bdnE8bh06VjzUAoHfZIGJmy0AwOT8dQ7fCFSppE1KwfROw6NggBe6UeBRx++06x4VrpX5p61rVU=
    - secure: T/1L86w/kzPsghGC0fzytRhk4i2zbXGBZmX2E8R1pxpaXw2VGskfEYhhotSt0qZ0w3Aj/+HFv+/syeCbOf0JI1/udpkbmkapmoSn0JGiSYbBwUwJ6EZKCneWhXiTe6x0cc0IKSjXcFPRFsjXDbUyYxGabxABMmaf/EMfl6rq6zQ=
