---
.travis.yml:
  secure_global_env:
    # PUBLISHER_PASSWORD
    - "X9oQvqCoFOieEgMoSrylt7/sbuGAyIu5EHQOFDTXIM9PzZe2gkxN41GuJ0cXpvd5UlI9ADVl47mmxqYhosLFE3JWSXMWwFSJSoDG3bKHj1y694Pt+LW7ezqn+uXqBHaIoC1mf1vHl1CehR6cRj7TI2H3YHklNll0/Cjuoa9hG5o="
Gemfile:
  optional:
  - gem: serverspec
  - gem: beaker
  - gem: beaker-rspec
